package app.logdate.server.openapi.schemadocs

import app.logdate.server.openapi.SchemaDoc

/** Descriptions for the device approval request, opaque transfer and account key shapes. */
internal object DeviceSchemaDocs {
    val docs =
        mapOf(
            "CreateEnrollmentRequest" to
                SchemaDoc(
                    "A new device's request to receive its existing account encryption identity.",
                    mapOf(
                        "deviceName" to "The device name shown for human confirmation on the approving phone.",
                        "publicKey" to "The device's ephemeral X25519 public key in unpadded base64url.",
                        "claimSecret" to "The optional short-lived secret generated by an unsigned-in device for a phone-first connection.",
                        "confirmationCode" to "The optional six-digit code displayed on the unsigned-in device for phone-first approval.",
                    ),
                ),
            "EnrollmentView" to
                SchemaDoc(
                    "The account-bound, short-lived device approval request without its encrypted envelope.",
                    mapOf(
                        "id" to "The request UUID encoded in the device's pairing QR code.",
                        "deviceName" to "The requesting device name shown to the approving phone.",
                        "publicKey" to "The requesting device's ephemeral X25519 public key.",
                        "confirmationCode" to "The six-digit code the person compares on both devices.",
                        "expiresAt" to "The request expiration time in Unix epoch milliseconds.",
                        "status" to "Pending, approved, or rejected while the request remains available.",
                    ),
                ),
            "ApproveEnrollmentRequest" to
                SchemaDoc(
                    "An existing device's encrypted, single-use transfer to the requesting device.",
                    mapOf(
                        "confirmationCode" to "The six-digit code displayed on the requesting device.",
                        "encryptedEnvelope" to "Opaque encrypted identity and optional media keys; the server never opens it.",
                    ),
                ),
            "ConsumedEnrollment" to
                SchemaDoc(
                    "The opaque key envelope returned once to the approved device.",
                    mapOf("encryptedEnvelope" to "The encrypted transfer sealed for the device's ephemeral public key."),
                ),
            "ClaimedEnrollment" to
                SchemaDoc(
                    "The state of a phone-created device connection and its one-use encrypted transfer when approved.",
                    mapOf(
                        "id" to "The short-lived connection request UUID.",
                        "accountId" to "The account UUID supplied by the signed-in approving phone.",
                        "publicKey" to "The device ephemeral X25519 public key bound to this connection.",
                        "confirmationCode" to "The six-digit code confirmed on both devices.",
                        "status" to "Pending until the phone approves or rejects the connection; a final result is returned once.",
                        "encryptedEnvelope" to
                            "The opaque encrypted transfer, present only after approval and readable until acknowledgement or expiry.",
                    ),
                ),
            "AccountKeyEnvelope" to
                SchemaDoc(
                    "Client-encrypted account keys, bound to a passkey credential and account.",
                    mapOf("ciphertext" to "Canonical base64 LDKE1 ciphertext; the server never has the unlock secret."),
                ),
        )
}
