package app.logdate.server.openapi.schemadocs

import app.logdate.server.openapi.SchemaDoc

/** Descriptions for the device approval request, opaque transfer and account key shapes. */
internal object DeviceSchemaDocs {
    val docs =
        mapOf(
            "CreateEnrollmentRequest" to
                SchemaDoc(
                    "A new Mac's request to receive its existing account encryption identity.",
                    mapOf(
                        "deviceName" to "The Mac name shown for human confirmation on the approving phone.",
                        "publicKey" to "The Mac's ephemeral X25519 public key in unpadded base64url.",
                        "claimSecret" to "The optional short-lived secret generated by an unsigned-in device for a phone-first connection.",
                        "confirmationCode" to "The optional six-digit code displayed on the unsigned-in Mac for phone-first approval.",
                    ),
                ),
            "EnrollmentView" to
                SchemaDoc(
                    "The account-bound, short-lived device approval request without its encrypted envelope.",
                    mapOf(
                        "id" to "The request UUID encoded in the Mac's pairing QR code.",
                        "deviceName" to "The requesting Mac name shown to the approving phone.",
                        "publicKey" to "The requesting Mac's ephemeral X25519 public key.",
                        "confirmationCode" to "The six-digit code the person compares on both devices.",
                        "expiresAt" to "The request expiration time in Unix epoch milliseconds.",
                        "status" to "Pending, approved, or rejected while the request remains available.",
                    ),
                ),
            "ApproveEnrollmentRequest" to
                SchemaDoc(
                    "An existing device's encrypted, single-use transfer to the requesting Mac.",
                    mapOf(
                        "confirmationCode" to "The six-digit code displayed on the requesting Mac.",
                        "encryptedEnvelope" to "Opaque encrypted identity and optional media keys; the server never opens it.",
                    ),
                ),
            "ConsumedEnrollment" to
                SchemaDoc(
                    "The opaque key envelope returned once to the approved Mac.",
                    mapOf("encryptedEnvelope" to "The encrypted transfer sealed for the Mac's ephemeral public key."),
                ),
            "ClaimedEnrollment" to
                SchemaDoc(
                    "The state of a phone-created Mac connection and its one-use encrypted transfer when approved.",
                    mapOf(
                        "id" to "The short-lived connection request UUID.",
                        "accountId" to "The account UUID supplied by the signed-in approving phone.",
                        "publicKey" to "The Mac ephemeral X25519 public key bound to this connection.",
                        "confirmationCode" to "The six-digit code confirmed on both devices.",
                        "status" to "Pending until the phone approves or rejects the connection; a final result is returned once.",
                        "encryptedEnvelope" to
                            "The opaque encrypted transfer, present only after approval and readable until acknowledgement or expiry.",
                    ),
                ),
            "AccountKeys" to
                SchemaDoc(
                    "The account's encryption keys, held by the server so a newly signed-in device can recover them.",
                    mapOf(
                        "identityKey" to "The account identity key: exactly 32 bytes in canonical standard base64.",
                        "mediaKey" to "The account media encryption key: exactly 32 bytes in canonical standard base64.",
                    ),
                ),
        )
}
