package app.logdate.shared.model

import kotlinx.serialization.Serializable

/**
 * AI-generated narrative understanding of a week's journal content.
 *
 * This captures the STORY of the week - what it was about, how it felt,
 * and the key moments that defined it - rather than mechanical statistics.
 *
 * Generated by WeekNarrativeSynthesizer using AI analysis of journal entries,
 * photos, locations, and people encountered.
 */
@Serializable
data class WeekNarrative(
    /**
     * Main themes that characterized the week.
     *
     * Examples:
     * - ["vacation", "exploration", "culinary adventure"]
     * - ["relationship stress", "work pressure", "gaming as therapy"]
     * - ["milestone achieved", "celebration", "reflection"]
     */
    val themes: List<String>,

    /**
     * Overall emotional tone of the week.
     *
     * Examples:
     * - "excited and refreshed"
     * - "stressful but resilient"
     * - "bittersweet"
     * - "triumphant"
     */
    val emotionalTone: String,

    /**
     * Key story beats - the defining moments of the week.
     *
     * Typically 4-7 beats that form the narrative arc.
     */
    val storyBeats: List<StoryBeat>,

    /**
     * Overall narrative summary in 2-3 sentences.
     *
     * Example:
     * "You explored the California coast, finally finding that hidden beach
     * you'd been searching for. Evenings were dedicated to the taco truck tour
     * you'd been planning. Sometimes the best trips are the ones you've dreamed about."
     */
    val overallNarrative: String
)

/**
 * A key moment or beat in the week's story.
 *
 * Story beats are the defining moments that shape the narrative -
 * not just events, but moments with context and meaning.
 */
@Serializable
data class StoryBeat(
    /**
     * Description of the moment.
     *
     * Examples:
     * - "Found the hidden beach"
     * - "Sarah being away hit harder than expected"
     * - "Raid team finally cleared Mythic"
     */
    val moment: String,

    /**
     * Context and meaning of this moment.
     *
     * Examples:
     * - "Long-anticipated goal achieved"
     * - "Unexpected loneliness during relationship separation"
     * - "Gaming friends providing support during tough week"
     */
    val context: String,

    /**
     * Emotional weight or tone of this moment.
     *
     * Examples:
     * - "triumphant"
     * - "melancholy"
     * - "grateful"
     * - "frustrated"
     */
    val emotionalWeight: String,

    /**
     * IDs of journal content (entries, photos, videos) that serve as evidence.
     *
     * These are the specific quotes, photos, or moments that illustrate this beat.
     * Used to find supporting material when creating rewind panels.
     */
    val evidenceIds: List<String>
)
