package app.logdate.shared.model

import kotlinx.serialization.Serializable
import kotlin.jvm.JvmInline

/**
 * AI-generated narrative understanding of a week's journal content.
 *
 * This captures the STORY of the week - what it was about, how it felt,
 * and the key moments that defined it - rather than mechanical statistics.
 *
 * Generated by WeekNarrativeSynthesizer using AI analysis of journal entries,
 * photos, locations, and people encountered.
 */
@Serializable
data class WeekNarrative(
    /**
     * Main themes that characterized the week.
     *
     * Examples:
     * - ["vacation", "exploration", "culinary adventure"]
     * - ["relationship stress", "work pressure", "gaming as therapy"]
     * - ["milestone achieved", "celebration", "reflection"]
     */
    val themes: List<String>,
    /**
     * Overall emotional tone of the week.
     *
     * Examples:
     * - "excited and refreshed"
     * - "stressful but resilient"
     * - "bittersweet"
     * - "triumphant"
     */
    val emotionalTone: String,
    /**
     * Key story beats - the defining moments of the week.
     *
     * Typically 4-7 beats that form the narrative arc.
     */
    val storyBeats: List<StoryBeat>,
    /**
     * Overall narrative summary in 2-3 sentences.
     *
     * Example:
     * "You explored the California coast, finally finding that hidden beach
     * you'd been searching for. Evenings were dedicated to the taco truck tour
     * you'd been planning. Sometimes the best trips are the ones you've dreamed about."
     */
    val overallNarrative: String,
    /**
     * 2-3 noticing prompts the AI invented from this week's actual content.
     *
     * These are NOT templated reflection / gratitude / growth questions — those are the
     * tired wellness-app playbook every journaling app already ships. They're connections
     * the AI drew between specific moments in the user's week and surfaced as invitations
     * to look closer. The prompt should feel like the rewind itself is paying attention:
     *
     *  - "You wrote about the rain three times this week. What was different about
     *     Wednesday's storm?"
     *  - "Sarah came up in five entries. The last was Friday at the bookshop. What
     *     stayed with you?"
     *  - "You spent more nights at the coffee shop than your apartment this week. Was
     *     that on purpose?"
     *
     * Empty when synthesis didn't produce prompts. The Rewind UI shows these as panels at
     * the end of the story; an empty list means no prompt panels are shown at all — there
     * are no template fallbacks.
     */
    val reflectionPrompts: List<ReflectionPrompt> = emptyList(),
    /**
     * 2-4 verbatim lines pulled straight from the user's own journal entries this week.
     *
     * Not paraphrased, not reworded — the actual sentence as the user typed it, surfaced
     * as a highlight because it captures something the AI noticed was sharper or more
     * honest than the surrounding prose. This is the "Spotify Wrapped" beat where the user
     * sees their own best line back at them and recognizes it as something they wrote.
     *
     * Empty when synthesis didn't surface any quotes.
     */
    val highlightedQuotes: List<HighlightedQuote> = emptyList(),
    /**
     * Weather summary for the week's primary location and date range.
     *
     * Fetched in parallel with the LLM call by the synthesizer when the caller passes
     * a primary location. Null when no location was supplied or when the weather fetch
     * failed — the synthesizer treats weather as best-effort context, never blocking
     * the narrative on it.
     */
    val weatherContext: WeatherContext? = null,
)

/**
 * One AI-invented "noticing" tied to a specific week's content.
 *
 * Each prompt has two parts. [observation] is the connection the AI noticed in the user's
 * data — short, factual, framed in their own life ("You spent four nights writing past
 * midnight"). [invitation] is the open-ended question the observation leads into ("Was
 * that on purpose, or did the week run away from you?"). The split lets the UI render
 * both parts with different weight: the observation as a quiet header that grounds the
 * prompt in real data, the invitation as the call to actually look.
 *
 * No category, no taxonomy — every prompt is unique to the week that produced it.
 */
@Serializable
data class ReflectionPrompt(
    val observation: String,
    val invitation: String,
) {
    /**
     * A stable identifier for this prompt derived purely from its text.
     *
     * Two prompts with the same observation and invitation always produce the same key,
     * which lets a typed response survive a re-synthesis of the rewind: as long as the
     * AI picks the same noticing again, the saved response reattaches automatically.
     * If the AI invents a different prompt, the response is intentionally orphaned.
     */
    val key: ReflectionPromptKey
        get() = ReflectionPromptKey.of(this)
}

/**
 * A content-derived identifier for a [ReflectionPrompt].
 *
 * Wraps a 16-character hex string produced by FNV-1a-64 over the prompt's text. Not
 * cryptographic — it exists to disambiguate prompts so saved responses can reattach
 * across re-syntheses, not to defend against tampering.
 */
@JvmInline
@Serializable
value class ReflectionPromptKey(
    val value: String,
) {
    companion object {
        fun of(prompt: ReflectionPrompt): ReflectionPromptKey = of(prompt.observation, prompt.invitation)

        fun of(
            observation: String,
            invitation: String,
        ): ReflectionPromptKey {
            // FNV-1a-64 over UTF-8 bytes of "observation\u0000invitation". The null
            // separator keeps swapped fields from colliding (e.g. "ab","c" vs "a","bc").
            val bytes = ("$observation\u0000$invitation").encodeToByteArray()
            var hash = 0xcbf29ce484222325uL
            val prime = 0x100000001b3uL
            for (b in bytes) {
                hash = hash xor (b.toLong() and 0xffL).toULong()
                hash = (hash * prime) and 0xffffffffffffffffuL
            }
            return ReflectionPromptKey(hash.toString(16).padStart(16, '0'))
        }
    }
}

/**
 * A verbatim quote pulled from one of the user's actual journal entries.
 *
 * The point of a highlighted quote is recognition — the user reads the line and goes
 * "oh yeah, I wrote that, and it's true". So [text] must be the exact characters the
 * user typed. The AI may not edit, paraphrase, or summarize. [whyItHits] is a one-line
 * note from the AI explaining why it picked this line out of the surrounding entry —
 * displayed quietly underneath as the rewind's reason for caring. [sourceEntryId] ties
 * the quote back to the entry it came from so the UI could deep-link if the user taps it.
 */
@Serializable
data class HighlightedQuote(
    val text: String,
    val whyItHits: String,
    val sourceEntryId: String,
)

/**
 * A key moment or beat in the week's story.
 *
 * Story beats are the defining moments that shape the narrative -
 * not just events, but moments with context and meaning.
 */
@Serializable
data class StoryBeat(
    /**
     * Description of the moment.
     *
     * Examples:
     * - "Found the hidden beach"
     * - "Sarah being away hit harder than expected"
     * - "Raid team finally cleared Mythic"
     */
    val moment: String,
    /**
     * Context and meaning of this moment.
     *
     * Examples:
     * - "Long-anticipated goal achieved"
     * - "Unexpected loneliness during relationship separation"
     * - "Gaming friends providing support during tough week"
     */
    val context: String,
    /**
     * Emotional weight or tone of this moment.
     *
     * Examples:
     * - "triumphant"
     * - "melancholy"
     * - "grateful"
     * - "frustrated"
     */
    val emotionalWeight: String,
    /**
     * IDs of journal content (entries, photos, videos) that serve as evidence.
     *
     * These are the specific quotes, photos, or moments that illustrate this beat.
     * Used to find supporting material when creating rewind panels.
     */
    val evidenceIds: List<String>,
)
