package app.logdate.client.intelligence.rewind.local

/**
 * English stopword list used by local theme extraction to filter out grammatical
 * filler before frequency-weighting content words. Kept narrow on purpose — too
 * aggressive a list would suppress legitimate themes ("we", "us", "my" can be
 * meaningful signals about who's around).
 *
 * Source: a curated subset of the classic SMART/snowball English stopword set,
 * trimmed to the function-word core. Held inline rather than loaded from a JSON
 * resource because a hardcoded constant is the simplest cross-platform shape and
 * the set is small.
 */
object StopwordList {
    private val WORDS: Set<String> =
        setOf(
            // Articles / determiners
            "a",
            "an",
            "the",
            "this",
            "that",
            "these",
            "those",
            // Pronouns (kept narrow — we/us/my carry social signal)
            "i",
            "he",
            "she",
            "it",
            "they",
            "them",
            "him",
            "her",
            "his",
            "hers",
            "its",
            "their",
            "theirs",
            // Conjunctions
            "and",
            "or",
            "but",
            "nor",
            "so",
            "yet",
            "for",
            "if",
            "because",
            "although",
            "though",
            "while",
            "whereas",
            // Prepositions
            "of",
            "to",
            "in",
            "on",
            "at",
            "by",
            "with",
            "from",
            "into",
            "onto",
            "upon",
            "about",
            "as",
            "out",
            "up",
            "down",
            "over",
            "under",
            "between",
            "through",
            "during",
            "before",
            "after",
            // Common verbs (be/have/do)
            "be",
            "am",
            "are",
            "is",
            "was",
            "were",
            "been",
            "being",
            "have",
            "has",
            "had",
            "having",
            "do",
            "does",
            "did",
            "done",
            "doing",
            // Modals / auxiliaries
            "can",
            "could",
            "shall",
            "should",
            "will",
            "would",
            "may",
            "might",
            "must",
            "ought",
            // Conjunctive adverbs / fillers
            "then",
            "than",
            "also",
            "just",
            "very",
            "too",
            "still",
            "now",
            "here",
            "there",
            "where",
            "when",
            "why",
            "how",
            "what",
            "which",
            "who",
            "whom",
            "whose",
            // Negation / quantifiers
            "no",
            "not",
            "nor",
            "none",
            "any",
            "some",
            "all",
            "each",
            "every",
            "few",
            "many",
            "much",
            "more",
            "most",
            "less",
            "least",
            "such",
            "only",
            "own",
            "same",
            // Filler
            "yes",
            "ok",
            "okay",
            "right",
            "well",
            "really",
            "actually",
        )

    fun contains(word: String): Boolean = WORDS.contains(word.trim().lowercase())

    val size: Int get() = WORDS.size
}
