package app.logdate.server.routes.docs

import app.logdate.server.openapi.ApiTags
import app.logdate.server.routes.ApproveEnrollmentRequest
import app.logdate.server.routes.ClaimedEnrollment
import app.logdate.server.routes.ConsumedEnrollment
import app.logdate.server.routes.CreateEnrollmentRequest
import app.logdate.server.routes.EnrollmentView
import app.logdate.server.routes.ErrorCase
import app.logdate.server.routes.bearerOperation
import app.logdate.server.routes.created
import app.logdate.server.routes.jsonBody
import app.logdate.server.routes.noContent
import app.logdate.server.routes.ok
import app.logdate.server.routes.publicOperation
import app.logdate.server.routes.syncError
import app.logdate.shared.model.AccountTokens
import io.github.smiley4.ktoropenapi.config.RequestConfig
import io.github.smiley4.ktoropenapi.config.RouteConfig
import io.ktor.http.HttpStatusCode

private const val EXAMPLE_ID = "4d90d8dc-49b2-4ba1-8c20-529b80c77542"
private const val EXAMPLE_PUBLIC_KEY = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
private const val EXAMPLE_CODE = "413827"

private val pending = EnrollmentView(EXAMPLE_ID, "Willie's Mac", EXAMPLE_PUBLIC_KEY, EXAMPLE_CODE, 1_790_793_600_000, "pending")

private fun RequestConfig.enrollmentId() {
    pathParameter<String>("id") {
        description = "The short-lived transfer request ID shown in the Mac's pairing QR code."
        example("Example") { value = EXAMPLE_ID }
    }
}

/** Documentation for the authenticated, one-use device approval relay. */
internal object DeviceEnrollmentDocs {
    val claim: RouteConfig.() -> Unit = {
        publicOperation(
            "claimDeviceEnrollment",
            ApiTags.DEVICES,
            "Receive an approved device connection",
            "A new device presents its short-lived, high-entropy connection secret to check approval. The result can be retried after a lost response. An approved transfer is deleted when the new device consumes it with its transferred account session.",
        )
        request {
            headerParameter<String>("X-LogDate-Claim-Secret") {
                description = "The unpadded base64url secret generated by the new device and included in its pairing QR code."
                required = true
                example("Example") { value = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" }
            }
        }
        response {
            ok(
                "The connection state and, once approved, the one-use encrypted transfer.",
                ClaimedEnrollment(EXAMPLE_ID, EXAMPLE_ID, EXAMPLE_PUBLIC_KEY, EXAMPLE_CODE, "approved", "encrypted-envelope"),
            )
            syncError(
                HttpStatusCode.BadRequest,
                ErrorCase("INVALID_CLAIM", "The connection secret is invalid.", "Invalid connection claim"),
            )
            syncError(
                HttpStatusCode.NotFound,
                ErrorCase("NOT_FOUND", "The connection expired or its final result was consumed.", "Connection unavailable"),
            )
            syncServerError()
        }
    }

    val create: RouteConfig.() -> Unit = {
        bearerOperation(
            "createDeviceEnrollment",
            ApiTags.DEVICES,
            "Start device approval",
            "Creates a five-minute approval request for a signed-in device. When an existing device scans a connection code, repeating the same account and QR details returns the original request. The response contains the code and public key that the approving device must confirm before sending an encrypted envelope.",
        )
        request {
            jsonBody(
                CreateEnrollmentRequest("Willie's Mac", EXAMPLE_PUBLIC_KEY),
                "The new device's display name and ephemeral X25519 public key, encoded as base64url. A scanned connection code also supplies its claim secret and confirmation code.",
            )
        }
        response {
            created("The device approval request is ready to display.", pending, "/api/v1/device-enrollments/$EXAMPLE_ID")
            syncError(
                HttpStatusCode.BadRequest,
                ErrorCase("INVALID_ENROLLMENT", "The device name or public key is invalid.", "Invalid device name or public key"),
            )
            syncError(
                HttpStatusCode.Conflict,
                ErrorCase("ENROLLMENT_CONFLICT", "The connection secret belongs to a different request.", "Connection code already used"),
            )
            syncUnauthorized()
            syncServerError()
        }
    }

    val get: RouteConfig.() -> Unit = {
        bearerOperation(
            "getDeviceEnrollment",
            ApiTags.DEVICES,
            "Read device approval",
            "Returns the account-bound request, including its Mac name, confirmation code, expiry, and status. The encrypted key envelope is never included in this read response.",
        )
        request { enrollmentId() }
        response {
            ok("The request is still available for this account.", pending)
            syncError(HttpStatusCode.BadRequest, ErrorCase("INVALID_ENROLLMENT", "The request ID is not a UUID.", "Invalid request ID"))
            syncError(
                HttpStatusCode.NotFound,
                ErrorCase(
                    "NOT_FOUND",
                    "The request was cancelled, consumed, expired, or belongs to another account.",
                    "Enrollment unavailable",
                ),
            )
            syncUnauthorized()
            syncServerError()
        }
    }

    val transfer: RouteConfig.() -> Unit = {
        bearerOperation(
            "getDeviceEnrollmentTransfer",
            ApiTags.DEVICES,
            "Read approved transfer",
            "Returns the approved encrypted key envelope to the requesting device without deleting it. The device may retry this read after an interrupted response, then acknowledges the transfer after saving its keys.",
        )
        request { enrollmentId() }
        response {
            ok(
                "The approved encrypted envelope remains available until acknowledgement or expiry.",
                ConsumedEnrollment("encrypted-envelope"),
            )
            syncError(HttpStatusCode.BadRequest, ErrorCase("INVALID_ENROLLMENT", "The request ID is not a UUID.", "Invalid request ID"))
            syncError(
                HttpStatusCode.NotFound,
                ErrorCase("NOT_FOUND", "The request expired, was removed, or belongs to another account.", "Enrollment unavailable"),
            )
            syncError(
                HttpStatusCode.Conflict,
                ErrorCase("ENROLLMENT_UNAVAILABLE", "The request has not been approved.", "Enrollment unavailable"),
            )
            syncUnauthorized()
            syncServerError()
        }
    }

    val session: RouteConfig.() -> Unit = {
        bearerOperation(
            "issueDeviceEnrollmentSession",
            ApiTags.DEVICES,
            "Issue the new device's session",
            """
            The approving device calls this for a pending request before **Approve a new device**, then seals the
            returned tokens into the encrypted envelope. The tokens are a fresh sign-in for the account, separate
            from the caller's own: the new device refreshes them on its own, and logging out on either device
            leaves the other signed in.

            Each request issues one session. Repeated calls return identical tokens while the request is
            pending, including after a lost response or server restart. Approval, rejection, cancellation,
            and expiry end that replay window. The response is marked `Cache-Control: no-store`.
            """,
        )
        request { enrollmentId() }
        response {
            ok(
                "A new access and refresh token pair for the requesting device.",
                AccountTokens("eyJhbGciOiJIUzI1NiJ9.access.signature", "eyJhbGciOiJIUzI1NiJ9.refresh.signature"),
            )
            syncError(HttpStatusCode.BadRequest, ErrorCase("INVALID_ENROLLMENT", "The request ID is not a UUID.", "Invalid request ID"))
            syncError(
                HttpStatusCode.NotFound,
                ErrorCase(
                    "NOT_FOUND",
                    "The request expired, was removed or belongs to another account, or the account no longer exists.",
                    "Enrollment unavailable",
                ),
            )
            syncError(
                HttpStatusCode.Conflict,
                ErrorCase("ENROLLMENT_UNAVAILABLE", "The request is no longer pending.", "Enrollment unavailable"),
            )
            syncUnauthorized()
            syncServerError()
        }
    }

    val approve: RouteConfig.() -> Unit = {
        bearerOperation(
            "approveDeviceEnrollment",
            ApiTags.DEVICES,
            "Approve a new device",
            "An existing signed-in device sends an opaque encrypted key envelope after the person confirms the Mac name and code. Approval can happen only once while the request is pending.",
        )
        request {
            enrollmentId()
            jsonBody(
                ApproveEnrollmentRequest(EXAMPLE_CODE, "encrypted-envelope"),
                "The matching six-digit code and an encrypted envelope that only the requesting Mac can open.",
            )
        }
        response {
            noContent("The encrypted transfer is waiting for the Mac to consume it.")
            syncError(
                HttpStatusCode.BadRequest,
                ErrorCase("INVALID_ENROLLMENT", "The code or envelope has an invalid shape.", "Invalid approval"),
            )
            syncError(
                HttpStatusCode.Conflict,
                ErrorCase("ENROLLMENT_UNAVAILABLE", "The request is not pending for this account and code.", "Enrollment unavailable"),
            )
            syncUnauthorized()
            syncServerError()
        }
    }

    val consume: RouteConfig.() -> Unit = {
        bearerOperation(
            "consumeDeviceEnrollment",
            ApiTags.DEVICES,
            "Acknowledge approved keys",
            "The requesting device acknowledges an encrypted transfer after saving its identity key. The server deletes it in the same transaction, so later claims or repeated consume calls cannot return the envelope.",
        )
        request { enrollmentId() }
        response {
            ok("The encrypted envelope is returned once and removed from the server.", ConsumedEnrollment("encrypted-envelope"))
            syncError(HttpStatusCode.BadRequest, ErrorCase("INVALID_ENROLLMENT", "The request ID is not a UUID.", "Invalid request ID"))
            syncError(
                HttpStatusCode.Conflict,
                ErrorCase("ENROLLMENT_UNAVAILABLE", "The request is not approved, expired, or already consumed.", "Enrollment unavailable"),
            )
            syncUnauthorized()
            syncServerError()
        }
    }

    val cancel: RouteConfig.() -> Unit = {
        bearerOperation(
            "cancelDeviceEnrollment",
            ApiTags.DEVICES,
            "Cancel device approval",
            "The requesting Mac cancels an unfinished approval. The server deletes the request and any encrypted envelope, so a later approval or consume cannot succeed.",
        )
        request { enrollmentId() }
        response {
            noContent("The request and any queued envelope have been removed.")
            syncError(HttpStatusCode.BadRequest, ErrorCase("INVALID_ENROLLMENT", "The request ID is not a UUID.", "Invalid request ID"))
            syncError(
                HttpStatusCode.NotFound,
                ErrorCase("NOT_FOUND", "The request does not belong to this account or was removed.", "Enrollment unavailable"),
            )
            syncUnauthorized()
            syncServerError()
        }
    }

    val reject: RouteConfig.() -> Unit = {
        bearerOperation(
            "rejectDeviceEnrollment",
            ApiTags.DEVICES,
            "Reject device approval",
            "An existing signed-in device rejects a request shown on its scanner. The requesting device can read the rejected status until the request expires or is cancelled.",
        )
        request { enrollmentId() }
        response {
            noContent("The request has been rejected.")
            syncError(HttpStatusCode.BadRequest, ErrorCase("INVALID_ENROLLMENT", "The request ID is not a UUID.", "Invalid request ID"))
            syncError(
                HttpStatusCode.NotFound,
                ErrorCase("NOT_FOUND", "The request does not belong to this account or was removed.", "Enrollment unavailable"),
            )
            syncUnauthorized()
            syncServerError()
        }
    }
}
