package app.logdate.client.location.places

import android.content.Context
import android.content.pm.PackageManager
import app.logdate.shared.model.Location
import com.google.android.gms.maps.model.LatLng
import com.google.android.libraries.places.api.Places
import com.google.android.libraries.places.api.model.CircularBounds
import com.google.android.libraries.places.api.model.Place
import com.google.android.libraries.places.api.net.PlacesClient
import com.google.android.libraries.places.api.net.SearchNearbyRequest
import io.github.aakira.napier.Napier
import kotlinx.coroutines.tasks.await

/**
 * Searches for nearby places (restaurants, parks, etc.) using the Google Places SDK.
 *
 * Implements [ExternalPlacesProvider]. The API key is resolved at init from the
 * `com.google.android.geo.API_KEY` manifest metadata or the `google_api_key` string resource
 * generated by the google-services plugin. Logs an error and disables lookups if no key is found.
 */
class GooglePlacesExternalPlacesProvider(
    private val context: Context,
) : ExternalPlacesProvider {
    companion object {
        /** Radius of the circular search area around the given location, in meters. */
        private const val SEARCH_RADIUS_METERS = 250.0

        /** Maximum number of place results to return per search. */
        private const val MAX_RESULTS = 5

        /** Confidence score assigned to the closest result. */
        private const val BASE_CONFIDENCE = 95

        /** Confidence decrease per position in the results list. */
        private const val CONFIDENCE_STEP = 10

        /** Lowest confidence score any result can receive. */
        private const val MIN_CONFIDENCE = 55
    }

    private val resolvedApiKey: String? = resolveApiKey()
    private val placesClient: PlacesClient? by lazy(::createPlacesClient)

    override suspend fun searchNearbyPlaces(location: Location): List<PlaceSuggestion> {
        val client = placesClient ?: return emptyList()

        return runCatching {
            val request =
                SearchNearbyRequest
                    .builder(
                        CircularBounds.newInstance(
                            LatLng(location.latitude, location.longitude),
                            SEARCH_RADIUS_METERS,
                        ),
                        listOf(
                            Place.Field.DISPLAY_NAME,
                            Place.Field.FORMATTED_ADDRESS,
                            Place.Field.LOCATION,
                            Place.Field.ID,
                            Place.Field.PRIMARY_TYPE,
                            Place.Field.PRIMARY_TYPE_DISPLAY_NAME,
                        ),
                    ).setMaxResultCount(MAX_RESULTS)
                    .setRankPreference(SearchNearbyRequest.RankPreference.DISTANCE)
                    .build()

            client
                .searchNearby(request)
                .await()
                .places
                .mapIndexedNotNull { index, place ->
                    val latLng = place.location ?: return@mapIndexedNotNull null
                    PlaceSuggestion(
                        name = place.displayName ?: place.primaryTypeDisplayName ?: place.formattedAddress ?: "Nearby place",
                        address = place.formattedAddress ?: "${latLng.latitude}, ${latLng.longitude}",
                        latitude = latLng.latitude,
                        longitude = latLng.longitude,
                        confidence = (BASE_CONFIDENCE - (index * CONFIDENCE_STEP)).coerceAtLeast(MIN_CONFIDENCE),
                        category = place.primaryTypeDisplayName ?: place.primaryType,
                        externalId = place.id,
                    )
                }
        }.onFailure { error ->
            Napier.w("Google Places nearby search failed", error)
        }.getOrDefault(emptyList())
    }

    private fun createPlacesClient(): PlacesClient? {
        val apiKey = resolvedApiKey ?: return null
        return runCatching {
            if (!Places.isInitialized()) {
                Places.initializeWithNewPlacesApiEnabled(context.applicationContext, apiKey)
            }
            Places.createClient(context.applicationContext)
        }.onFailure { error ->
            Napier.e("Failed to initialize Google Places client", error)
        }.getOrNull()
    }

    private fun resolveApiKey(): String? {
        val key =
            context.readGoogleMapsManifestApiKey()
                ?: context.readGoogleServicesApiKey().ifBlank { null }
        if (key == null) {
            Napier.e(
                "No Google Maps API key found. Ensure google-services.json is present or set com.google.android.geo.API_KEY in the manifest.",
            )
        }
        return key
    }
}

private fun Context.readGoogleServicesApiKey(): String = readStringResource("google_api_key")

private fun Context.readGoogleMapsManifestApiKey(): String? =
    runCatching {
        val metaData =
            packageManager
                .getApplicationInfo(packageName, PackageManager.GET_META_DATA)
                .metaData

        val resourceId = metaData?.getInt("com.google.android.geo.API_KEY") ?: 0
        when {
            resourceId != 0 -> readStringResource(resourceId).ifBlank { null }
            else -> metaData?.getString("com.google.android.geo.API_KEY")?.ifBlank { null }
        }
    }.getOrNull()

private fun Context.readStringResource(name: String): String {
    val resourceId = resources.getIdentifier(name, "string", packageName)
    return readStringResource(resourceId)
}

private fun Context.readStringResource(resourceId: Int): String =
    if (resourceId == 0) {
        ""
    } else {
        runCatching {
            getString(resourceId)
        }.getOrDefault("")
    }
