package app.logdate.feature.rewind.ui.overview

import kotlinx.datetime.LocalDate
import kotlin.uuid.Uuid

/**
 * UI state representing a historical rewind entry for display in the overview screen.
 *
 * @param uid The unique identifier of the underlying domain rewind entity
 * @param title The human-readable title/name assigned to this rewind
 * @param label Short descriptive label for the time period (e.g., "Week 42")
 * @param startDate Start date of the rewind period
 * @param endDate End date of the rewind period
 */
data class RewindHistoryUiState(
    val uid: Uuid,
    val title: String,
    val label: String,
    val startDate: LocalDate,
    val endDate: LocalDate,
    val milestone: MilestoneSummaryUiState? = null,
)

/**
 * Optional milestone marker rendered on a past-rewind card.
 *
 * Present only when the rewind was generated by milestone detection — see
 * `MilestoneRewindCoordinator` and `RewindRepository.tagAsMilestone`. Drives a
 * distinct card treatment so the user can tell at a glance that this rewind is
 * about a specific event in their life rather than a normal weekly recap.
 */
data class MilestoneSummaryUiState(
    val kind: MilestoneKindUiState,
    val summary: String,
)

/**
 * UI-friendly mirror of the domain `MilestoneKind` enum, kept in the feature module
 * so the overview composable doesn't drag in the intelligence layer.
 */
enum class MilestoneKindUiState {
    LOCATION_CHANGE,
}
