#!/usr/bin/env bash
# resolve-ios-app-version.sh
#
# Mirrors scripts/resolve-android-play-version.sh, emitting the same
# numeric build-number scheme so versions across the two platforms are
# directly comparable in support tickets and crash reports.
#
# Outputs (stdout + $GITHUB_OUTPUT):
#   base_tag                 e.g. ios-v1.2.3
#   current_tag              empty when HEAD isn't on a tag
#   marketing_version        e.g. 1.2.3
#   current_project_version  COMMIT_COUNT*1000 + (sha_short[0:5] hex % 1000)
#   short_sha                e.g. 7b2ac41
#   testflight_what_to_test  one-liner suitable for TestFlight metadata
#
# Side effect: writes iosApp/Configuration/Version.xcconfig with
#   MARKETING_VERSION = <…>
#   CURRENT_PROJECT_VERSION = <…>
# so xcodebuild -archive picks the same numbers up automatically. The
# project's main Config.xcconfig must `#include "Version.xcconfig"` for
# this to take effect (added separately as part of the rollout).

set -euo pipefail

TAG_PATTERN='ios-v[0-9]*.[0-9]*.[0-9]*'

log_error() {
    printf '[error] %s\n' "$1" >&2
}

write_output() {
    local key="$1"
    local value="$2"
    printf '%s=%s\n' "$key" "$value"
    if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
        printf '%s=%s\n' "$key" "$value" >> "$GITHUB_OUTPUT"
    fi
}

require_git_repo() {
    git rev-parse --show-toplevel >/dev/null 2>&1 || {
        log_error "This script must run inside the LogDate git repository."
        exit 1
    }
}

resolve_current_tag() {
    if [[ "${GITHUB_REF_TYPE:-}" == "tag" ]] && [[ "${GITHUB_REF_NAME:-}" == ios-v* ]]; then
        printf '%s' "$GITHUB_REF_NAME"
        return 0
    fi

    git tag --points-at HEAD --list 'ios-v*' | LC_ALL=C sort -V | tail -n 1
}

resolve_base_tag() {
    local current_tag
    current_tag="$(resolve_current_tag)"
    if [[ -n "$current_tag" ]]; then
        printf '%s' "$current_tag"
        return 0
    fi

    git describe --tags --match "$TAG_PATTERN" --abbrev=0 2>/dev/null || {
        log_error "No ios-v<major>.<minor>.<patch> tag is reachable from HEAD. Create an initial iOS release tag (e.g. ios-v1.0.0) before enabling automated TestFlight publishing."
        exit 1
    }
}

parse_semver() {
    local tag="$1"
    if [[ ! "$tag" =~ ^ios-v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
        log_error "Unsupported iOS release tag '$tag'. Expected format: ios-v<major>.<minor>.<patch>."
        exit 1
    fi

    MAJOR=$((10#${BASH_REMATCH[1]}))
    MINOR=$((10#${BASH_REMATCH[2]}))
    PATCH=$((10#${BASH_REMATCH[3]}))
    MARKETING_VERSION_BASE="${MAJOR}.${MINOR}.${PATCH}"
}

resolve_commit_metadata() {
    COMMIT_COUNT="$(git rev-list --count HEAD)"
    SHORT_SHA="$(git rev-parse --short=7 HEAD)"

    local hash_seed
    hash_seed="${SHORT_SHA:0:5}"
    HASH_FRAGMENT=$((16#$hash_seed % 1000))
}

resolve_commit_distance() {
    local tag="$1"
    DISTANCE="$(git rev-list --count "${tag}..HEAD")"
    if (( DISTANCE > 999 )); then
        log_error "Found ${DISTANCE} commits since ${tag}. Cut a new ios-v* tag before publishing more than 999 builds from the same base version."
        exit 1
    fi
}

resolve_marketing_version() {
    if [[ -n "$CURRENT_TAG" ]]; then
        # On a tagged commit, the App Store version is exactly the tag
        # (CFBundleShortVersionString accepts only X.Y.Z, no metadata).
        MARKETING_VERSION="$MARKETING_VERSION_BASE"
    else
        # On main, treat as the next pre-release of the base tag's series.
        # CFBundleShortVersionString tolerates a trailing identifier in
        # most contexts but the App Store rejects anything past X.Y.Z, so
        # we keep this restricted to the base — the build number carries
        # the per-commit uniqueness.
        MARKETING_VERSION="$MARKETING_VERSION_BASE"
    fi
}

resolve_current_project_version() {
    CURRENT_PROJECT_VERSION=$(( (COMMIT_COUNT * 1000) + HASH_FRAGMENT ))

    # CFBundleVersion is technically unbounded, but App Store Connect's
    # numeric handling and Apple's docs both treat it as a 32-bit int in
    # places. Match the Android cap so the schemes can't diverge.
    if (( CURRENT_PROJECT_VERSION > 2147483647 )); then
        log_error "Resolved CURRENT_PROJECT_VERSION ${CURRENT_PROJECT_VERSION} exceeds Apple's safe integer range."
        exit 1
    fi
}

resolve_release_metadata() {
    if [[ -n "$CURRENT_TAG" ]]; then
        TESTFLIGHT_WHAT_TO_TEST="Production candidate ${CURRENT_TAG#ios-v} (${SHORT_SHA})."
    else
        TESTFLIGHT_WHAT_TO_TEST="Internal build from main, ${DISTANCE} commits past ${BASE_TAG#ios-v} (${SHORT_SHA})."
    fi
}

write_version_xcconfig() {
    local repo_root
    repo_root="$(git rev-parse --show-toplevel)"
    local target="${repo_root}/iosApp/Configuration/Version.xcconfig"
    mkdir -p "$(dirname "$target")"
    cat > "$target" <<EOF
// Auto-generated by scripts/resolve-ios-app-version.sh — do not edit by hand.
// MARKETING_VERSION feeds CFBundleShortVersionString.
// CURRENT_PROJECT_VERSION feeds CFBundleVersion (the build number that
// monotonically increases across every TestFlight / App Store upload).
MARKETING_VERSION = ${MARKETING_VERSION}
CURRENT_PROJECT_VERSION = ${CURRENT_PROJECT_VERSION}
EOF
}

main() {
    require_git_repo

    BASE_TAG="$(resolve_base_tag)"
    CURRENT_TAG="$(resolve_current_tag)"
    parse_semver "$BASE_TAG"
    resolve_commit_metadata
    resolve_commit_distance "$BASE_TAG"
    resolve_marketing_version
    resolve_current_project_version
    resolve_release_metadata
    write_version_xcconfig

    write_output "base_tag" "$BASE_TAG"
    write_output "current_tag" "$CURRENT_TAG"
    write_output "marketing_version" "$MARKETING_VERSION"
    write_output "current_project_version" "$CURRENT_PROJECT_VERSION"
    write_output "commit_count" "$COMMIT_COUNT"
    write_output "distance" "$DISTANCE"
    write_output "short_sha" "$SHORT_SHA"
    write_output "hash_fragment" "$HASH_FRAGMENT"
    write_output "testflight_what_to_test" "$TESTFLIGHT_WHAT_TO_TEST"
}

main "$@"
